// Date precision is preserved: a publication year is never inflated to a day.
// firstProof is the earliest proof source established for this exact example in
// this catalog, not a universal priority certificate. Unknown dates stay null.
const undated = (note, source) => ({firstProof:null, dateKind:'First proof date not established', source, note, milestones:[]});
export const history = {
 one:undated('The one-element construction is immediate. No historical first-proof attribution is established here.','elementary'),
 c2:undated('Classical modular arithmetic. The displayed construction proves existence; a historical first proof is not identified.','elementary'),
 c4:undated('Classical modular arithmetic. The displayed construction proves existence; a historical first proof is not identified.','elementary'),
 v4:undated('The direct product construction is elementary. Naming and first discovery are different questions; no first-proof date is assigned.','elementary'),
 s3:undated('Permutations of three symbols give an explicit construction. A historical first-proof source is not established.','elementary'),
 q8:{...undated('Hamilton’s 1843 work constructs the quaternion algebra. This date is not asserted as the first proof of every listed property of Q₈.','hamilton'),milestones:[{date:'1843',kind:'Algebra construction',claim:'Quaternion multiplication, from which the eight-element group is obtained.',source:'hamilton',facts:[]}]},
 a5:undated('A₅ is classical. The reference proves its simplicity; the earliest original simplicity proof is not established here.','robinson'),
 z:undated('The additive integers are classical; a single original group-existence proof date is not identified.','elementary'),
 z2:undated('The direct product of two copies of ℤ gives existence. Later geometric properties have their own proof history.','ggt'),
 q:undated('The additive rationals are classical. The displayed elementary arguments prove the recorded algebraic properties.','elementary'),
 prufer:{firstProof:'1923',dateKind:'Original published construction located',source:'prufer1923',note:'Prüfer’s paper studies countable primary abelian groups. Only the publication year is established here.',milestones:[]},
 free2:{firstProof:'1882',dateKind:'Original published construction located',source:'dyck1882',note:'Dyck’s construction of abstract free groups supplies this rank-two example. Later approximation and analytic properties are separate results.',milestones:[]},
 freeinf:undated('The reduced-word construction extends to a countable alphabet. No separate first-proof date for this rank is established here.','free'),
 dihedral:undated('The group is explicitly C₂ * C₂. A first historical proof date is not established here.','ggt'),
 heisenberg:undated('Existence follows directly from multiplication of upper unitriangular integer matrices. The date of the first use of this exact discrete example is not established.','ggt'),
 lamplighter:{...undated('The restricted wreath-product construction is classical. The 1961 milestone concerns failure of finite presentability, not the first construction of the group.','robinson'),milestones:[{date:'1961',kind:'Published property proof',claim:'The lamplighter group is not finitely presented (Baumslag’s wreath-product theorem).',source:'baumslag1961',facts:['!fp']}]},
 grigorchuk:{firstProof:'1980',dateKind:'Original published construction',source:'grigorchuk1980',note:'The infinite finitely generated torsion group was constructed in 1980. Intermediate growth was announced in 1983, with the detailed proof published in 1984.',milestones:[{date:'1980',kind:'Construction',claim:'An infinite finitely generated torsion 2-group.',source:'grigorchuk1980',facts:['!finite','fg','torsion']},{date:'1983',kind:'Published announcement',claim:'The intermediate-growth result was announced.',source:'grigorchuk1983',facts:[]},{date:'1984',kind:'Detailed published proof',claim:'Intermediate growth and the negative solution of Day’s elementary-amenability question.',source:'grigorchuk1984',facts:['intermediate','!ea']}]},
 sl3z:{...undated('The integer matrix group predates property (T). The 1967 date belongs to Kazhdan’s rigidity theorem.','kazhdan'),milestones:[{date:'1967',kind:'Published property proof',claim:'Kazhdan’s property (T) for SL₃(ℤ).',source:'kazhdan1967',facts:['t']}]},
 higman:{firstProof:'1951-01',dateKind:'Original published construction',source:'higman1951',note:'Higman’s four-generator group is infinite and has no nontrivial finite quotients. Its acyclicity and finite classifying-space description are documented separately in the modern reference.',milestones:[]},
 grigorchuk98:{firstProof:'1998',dateKind:'Original published proof located',source:'grigorchuk98',note:'A finitely presented amenable group outside the elementary amenable class.',milestones:[{date:'1998',kind:'Published property proof',claim:'Finite presentability, amenability, and failure of elementary amenability for the same group.',source:'grigorchuk98',facts:['fp','amenable','!ea']}]},
 erschler:{firstProof:'2002-05',dateKind:'Earliest located preprint',source:'erschler2002',note:'The IHÉS preprint is dated May 2002; the journal article appeared on 1 February 2004.',milestones:[{date:'2002-05',kind:'Preprint',claim:'Intermediate growth without residual finiteness.',source:'erschler2002',facts:['intermediate','!rf']},{date:'2004-02-01',kind:'Journal publication',claim:'Publication in Journal of Algebra, volume 272.',source:'erschler',facts:[]}]},
 nekrashevych:{firstProof:'2020-08-11',dateKind:'Original construction preprint',source:'nekrashevych2020',note:'This entry is the construction containing the first Grigorchuk group. Earlier simple groups of intermediate growth were announced in a different 2016 paper.',milestones:[{date:'2016-01-06',kind:'Earlier examples in this class',claim:'First simple groups of intermediate growth; not the date of this specific 2020 construction.',source:'nekrashevych2016',facts:[]},{date:'2020-08-11',kind:'Construction preprint',claim:'A simple torsion group of intermediate growth containing the first Grigorchuk group.',source:'nekrashevych2020',facts:['!finite','fg','simple','torsion','intermediate','!exponent']}]},
 thompson:{firstProof:'1965',dateKind:'Construction date reported in the literature',source:'thompson',note:'Cannon–Floyd–Parry (1996) attribute the definitions to Richard Thompson in 1965. Their article is a later source, not a 1965 publication.',milestones:[{date:'1984',kind:'Detailed published property proof',claim:'Brown–Geoghegan establish the infinite-dimensional finiteness properties of F; their result was announced in 1983.',source:'brown1984',facts:[]}]},
 sauers:{firstProof:'2026-08-24',dateKind:'First registered formal proof',source:'palomar',note:'Sauers. The pinned v1 record was mechanically verified at 18:17:14 UTC and registered at 20:15:36 UTC on 24 August 2026.',milestones:[{date:'2026-08-24',kind:'Registered formal proof',claim:'The displayed finitely presented group is sofic and not MF in the Carrión–Dadarlat–Eckhardt operator-norm sense.',source:'palomar',facts:['fp','sofic','!mf']}],priority:{claim:'First non-MF group',attribution:'Sauers (author’s priority claim)',note:'The registry verifies the pinned formal result; its editorial record does not certify novelty.'},formal:{theorem:'ExplicitNonMF.explicit_sofic_not_MF',recordId:'PALOMAR-2026-08-24-000006',version:1,verifiedAt:'2026-08-24T18:17:14Z',commit:'f6ccc7a138b281eb6c4eedf111c6cbd37b4917ce',statement:'https://github.com/SauersML/group-approximation/blob/f6ccc7a138b281eb6c4eedf111c6cbd37b4917ce/Palomar/Challenge.lean',proof:'https://github.com/SauersML/group-approximation/blob/f6ccc7a138b281eb6c4eedf111c6cbd37b4917ce/PalomarSolution.lean',record:'https://data.palomar-registry.org/entries/PALOMAR-2026-08-24-000006-v1.json',assurance:'Palomar reports successful comparison, Lean kernel checking, and NanoDa checking of the pinned proof. Subsequent displayed deductions are not independently Lean-checked.'}}
};
export function formatDate(date){
 if(date===null)return 'Not established';
 if(/^\d{4}$/.test(date))return date;
 if(/^\d{4}-\d{2}$/.test(date))return new Intl.DateTimeFormat('en',{year:'numeric',month:'short',timeZone:'UTC'}).format(new Date(`${date}-01T12:00:00Z`));
 return new Intl.DateTimeFormat('en',{year:'numeric',month:'short',day:'numeric',timeZone:'UTC'}).format(new Date(`${date}T12:00:00Z`));
}
