// Date precision is preserved: a publication year is never inflated to a day.
// firstProof is the earliest proof source established for this exact example in
// this catalog, not a universal priority certificate. An entry without a located
// source keeps firstProof null and dateKind 'First proof date not established'.
export const history = {
 fournier_facio:{"firstProof": "2026-08-03", "dateKind": "Earliest archived construction proof", "source": "ff2026", "note": "Theorem 1.3 and §2 of v1 establish all recorded seed properties. The author reports an earlier homepage note on 1 August; the timeline uses the archived 3 August version. A revision followed on 14 August.", "milestones": [{"date": "2026-08-03", "kind": "Earliest archived construction proof", "claim": "The quotient G constructed in §2 is finitely presented, torsion-free, has property (T), and is not sofic.", "source": "ff2026", "facts": ["fp", "tf", "t", "!sofic"]}]},
 kun_thom:{"firstProof": "2026-08-20", "dateKind": "Pinned revised proof", "source": "kunThom2026", "note": "The preprint first appeared on 6 August. Versions 2 and 3 updated Theorem A; this record conservatively dates its certificate to v3 on 20 August, not a claim of first priority. Finite generation follows from finite generation of G and transitivity on G/Γ; one lamp together with generators of G suffices.", "milestones": [{"date": "2026-08-20", "kind": "Pinned revised proof", "claim": "W = (⊕_{G/Γ} C₂) ⋊ G, with Γ = EL₃(F₂[x₁,x₂,x₃]) and G = EL₃(F₂[x₁±¹,x₂±¹,x₃±¹]) ⋊ SL₃(ℤ), as in Theorem E. The lamp subgroup gives elements of order two.", "source": "kunThom2026", "facts": ["fg", "!sofic", "!tf"]}]},
 fisher_lodha:{"firstProof": "2026-08-26", "dateKind": "First construction preprint", "source": "fisherLodha2026", "note": "First arXiv submission, with n = 1. Local freeness is not recorded as freeness of the whole group.", "milestones": [{"date": "2026-08-26", "kind": "First construction preprint", "claim": "The n = 1 construction has first ℓ²-Betti number one and normal rank one. It is countable and locally free, hence locally indicable and torsion-free, but not finitely generated.", "source": "fisherLodha2026", "facts": ["tf", "li", "!fg"]}]},
 thom_lef:{"firstProof": "2008-10-13", "dateKind": "Earliest archived construction proof", "source": "thom2008", "note": "The first arXiv version supplies the LEF, Kazhdan, non-residually-finite example. This is distinct from the paper’s other hyperlinear example.", "milestones": [{"date": "2008-10-13", "kind": "Earliest archived construction proof", "claim": "Thom’s first example is locally embeddable in finite groups, has property (T), and is not residually finite.", "source": "thom2008", "facts": ["lef", "t", "!rf"]}]},
 leary_minasyan:{"firstProof": "2019-07-08", "dateKind": "First construction preprint", "source": "learyMinasyan2019", "note": "Example 9.4 with k = 1 and m = 2. The CAT(0) and non-biautomatic assertions are explicit; torsion-freeness follows from the HNN construction over ℤ². No assertion of automaticity is made.", "milestones": [{"date": "2019-07-08", "kind": "First construction preprint", "claim": "The group ⟨a,b,t | [a,b] = 1, tat⁻¹ = b, tb²t⁻¹ = a⁻²b⟩ in Example 9.4 is CAT(0) and not biautomatic. As an HNN extension of ℤ² it is torsion-free.", "source": "learyMinasyan2019", "facts": ["cat0", "!biautomatic", "tf"]}]},

 openai:{firstProof:'2026-08-01',dateKind:'First public non-soficity proof',source:'openaiAnnouncement',note:'OpenAI announced the non-soficity result on 1 August 2026 and released the original manuscript. This dates the non-soficity proof, not the earlier construction of the Leavitt algebra. No MF, hyperlinear, or finite-presentation property is assigned without a separate proof.',milestones:[{date:'2026-08-01',kind:'Public non-soficity proof',claim:'The unit group of the binary Leavitt algebra L_F₂(1,2) is not sofic (Chapter 3).',source:'openaiNonsofic',facts:['!sofic']}]},
 openaiFP:{firstProof:'2026-08-02',dateKind:'Public proof with Lean certificate',source:'openaiLean',note:'The Lean file in OpenAI’s ten-proofs repository (committed 2 August 2026 UTC, after the 1 August announcement) proves exists_finitelyPresented_nonsofic_group from the non-soficity of the binary Leavitt elementary group. Fournier-Facio’s August 2026 preprint states the same passage in print.',milestones:[{date:'2026-08-02',kind:'Lean-certified proof',claim:'A finitely presented non-sofic group exists: a finite multiplication table of a non-sofic group presents a finitely presented non-sofic group.',source:'openaiLean',facts:['fp','!sofic']},{date:'2026-08-03',kind:'Preprint remark',claim:'Non-soficity is open in the space of marked groups, so OpenAI’s example already yields a finitely presented non-sofic group.',source:'ff2026',facts:[]}]},
 burnside:{firstProof:'1968',dateKind:'Original published construction',source:'novikovAdian1968',note:'Novikov and Adian proved in 1968 that B(m, n) is infinite for odd n ≥ 4381. Non-amenability is Adian’s 1982 theorem. The later bound n ≥ 665 (Adian, 1975) is not separately sourced here.',milestones:[{date:'1968',kind:'Construction',claim:'An infinite finitely generated group of bounded exponent, for odd n ≥ 4381.',source:'novikovAdian1968',facts:['fg','!finite','exponent']},{date:'1982',kind:'Published property proof',claim:'Free Burnside groups of odd exponent n ≥ 665 are not amenable.',source:'adian1982',facts:['!amenable']}]},
 olshanskiiSapir:{firstProof:'2002-08-30',dateKind:'Earliest located preprint',source:'olshanskiiSapir2002',note:'The arXiv preprint is dated 30 August 2002; the journal article appeared in Publications Mathématiques de l’IHÉS, volume 96 (2003).',milestones:[{date:'2002-08-30',kind:'Preprint',claim:'Theorem 1.1: a finitely presented non-amenable torsion-by-cyclic group without free subgroups of rank two.',source:'olshanskiiSapir2002',facts:['fp','!amenable','!f2','!tf','!torsion']},{date:'2003',kind:'Journal publication',claim:'Publication in Publications Mathématiques de l’IHÉS, volume 96.',source:'olshanskiiSapir2003',facts:[]}]},
 juschenkoMonod:{firstProof:'2004-04',dateKind:'Earliest located preprint',source:'matui2006',note:'Matui’s April 2004 preprint proves the group simple, finitely generated and not finitely presented (International Journal of Mathematics, 2006). Amenability is the April 2012 Juschenko–Monod preprint, published in the Annals in 2013.',milestones:[{date:'2004-04',kind:'Preprint',claim:'Theorems 4.9, 5.4 and 5.7: the commutator subgroup of the topological full group of a minimal subshift is simple, finitely generated and never finitely presented.',source:'matui2006',facts:['simple','fg','!fp']},{date:'2012-04',kind:'Preprint',claim:'Topological full groups of minimal Cantor systems are amenable; the first infinite finitely generated simple amenable groups.',source:'juschenkoMonod2012',facts:['amenable','!finite']},{date:'2013',kind:'Journal publication',claim:'Publication in Annals of Mathematics, volume 178.',source:'juschenkoMonod2013',facts:[]}]},
 ershov:{firstProof:'2008',dateKind:'Original published proof located',source:'ershov2008',note:'Duke Mathematical Journal, volume 145 (2008). An earlier preprint is not separately dated here.',milestones:[{date:'2008',kind:'Published property proof',claim:'Proposition 8.4: an infinite residually finite torsion group with property (T). Corollary 8.5 answers de la Harpe’s question on residually finite torsion non-amenable groups.',source:'ershov2008',facts:['!finite','rf','torsion','t']}]},
 guba:{firstProof:'1986',dateKind:'Original published construction',source:'guba1986',note:'Izvestiya Akademii Nauk SSSR (1986); the English translation appeared in 1987.',milestones:[{date:'1986',kind:'Published construction',claim:'A nontrivial two-generated group with roots of every degree and unique extraction of roots.',source:'guba1986',facts:['fg','divisible','!trivial','tf']}]},
 cornulier:{firstProof:'2005-02',dateKind:'Earliest located preprint',source:'cornulier2007',note:'The arXiv preprint is dated February 2005; the article appeared in Proceedings of the AMS, volume 135 (2007).',milestones:[{date:'2005-02',kind:'Preprint',claim:'A finitely presented non-Hopfian group with Kazhdan’s property (T), answering a question of Ollivier and Wise.',source:'cornulier2007',facts:['fp','!hopfian','t']}]},
 one:{firstProof:'2005-10',dateKind:'Earliest located exact exposition; historical upper bound',source:'ggt',note:'Bowditch identifies the free abelian group of rank zero as the trivial group. This dates a located exact source, not the historical origin of the one-element group.',milestones:[]},
 c2:{firstProof:'1854',dateKind:'Original published classification located',source:'cayley1854',note:'Cayley’s first paper on abstract groups states that groups of prime order are cyclic; the order-two case is C₂. Only the publication year is used.',milestones:[{date:'1854',kind:'Published classification',claim:'The unique group of order two is cyclic.',source:'cayley1854',facts:['finite','cyclic']}]},
 c4:{firstProof:'1854',dateKind:'Original published classification located',source:'cayley1854',note:'Cayley classified the two groups of order four; the cyclic case is C₄. Only the publication year is used.',milestones:[{date:'1854',kind:'Published classification',claim:'The cyclic group is one of the two groups of order four.',source:'cayley1854',facts:['finite','cyclic']}]},
 v4:{firstProof:'1854',dateKind:'Original published classification located',source:'cayley1854',note:'Cayley classified the two groups of order four; the noncyclic case is the Klein four group. The modern name came later.',milestones:[{date:'1854',kind:'Published classification',claim:'The noncyclic group of order four is the second order-four form.',source:'cayley1854',facts:['finite','abelian','!cyclic']}]},
 s3:{firstProof:'1854',dateKind:'Original published classification located',source:'cayley1854',note:'Cayley’s order-six classification contains the nonabelian group now identified with S₃, alongside the cyclic group.',milestones:[{date:'1854',kind:'Published classification',claim:'The nonabelian order-six group is one of the two groups of order six.',source:'cayley1854',facts:['finite','!abelian']}]},
 q8:{firstProof:'1843-11-13',dateKind:'Original public communication',source:'hamilton',note:'Hamilton read Researches respecting Quaternions: First Series to the Royal Irish Academy on 13 November 1843. Its multiplication laws yield the eight-element quaternion group; this is not a date for every listed property of Q₈.',milestones:[{date:'1843-11-13',kind:'Public algebra communication',claim:'Quaternion multiplication, from which the eight-element group is obtained.',source:'hamilton',facts:[]}]},
 a5:{firstProof:'1870',dateKind:'Earliest located published proof for the exact group',source:'jordan1870',note:'Galois stated in his 29 May 1832 testamentary letter that the smallest simple group has order 60, but no proof of that statement survives in his papers. Jordan’s 1870 Traité gives a documented proof that Aₙ is simple for n ≥ 5, hence A₅.',milestones:[{date:'1832-05-29',kind:'Historical statement; proof not extant',claim:'Galois states, in modern terminology, that the smallest simple group has order 60.',source:'galois1832',facts:[]},{date:'1870',kind:'Published proof',claim:'Jordan proves the alternating group Aₙ is simple for n ≥ 5, hence A₅ is simple.',source:'jordan1870',facts:['simple']}]},
 z:{firstProof:'1882',dateKind:'Original free-group construction, rank-one specialization',source:'dyck1882',note:'Dyck’s construction of abstract free groups includes the rank-one free group, which is the infinite cyclic group ℤ. This is a located group-theoretic source, not a claim about the historical origin of the integers.',milestones:[{date:'1882',kind:'Published free-group construction',claim:'The rank-one free group gives the infinite cyclic group.',source:'dyck1882',facts:['free','cyclic','!finite']}]},
 z2:{firstProof:'2005-10',dateKind:'Earliest located exact exposition; historical upper bound',source:'ggt',note:'Bowditch presents ℤ² explicitly as the free abelian group of rank two. This is only an upper bound from the currently located literature.',milestones:[{date:'2005-10',kind:'Located exact exposition; historical upper bound',claim:'ℤ² is presented explicitly as the rank-two free abelian group.',source:'ggt',facts:['fg','abelian','!cyclic','!finite']}]},
 q:{firstProof:'1996',dateKind:'Earliest located exact exposition; historical upper bound',source:'robinson',note:'Robinson treats the additive group of rational numbers ℚ and identifies it as divisible and torsion-free. The textbook edition year is an upper bound, not a historical priority claim.',milestones:[{date:'1996',kind:'Located exact exposition; historical upper bound',claim:'The additive rationals are exhibited as an abelian, divisible, torsion-free group.',source:'robinson',facts:['abelian','divisible','tf']}]},
 prufer:{firstProof:'1923',dateKind:'Original published construction located',source:'prufer1923',note:'Prüfer’s paper studies countable primary abelian groups. Only the publication year is established here.',milestones:[]},
 free2:{firstProof:'1882',dateKind:'Original published construction located',source:'dyck1882',note:'Dyck’s construction of abstract free groups supplies this rank-two example. Later approximation and analytic properties are separate results.',milestones:[]},
 freeinf:{firstProof:'1927',dateKind:'Original published theorem yielding an infinite-rank free example',source:'schreier1927',note:'Schreier’s subgroup theorem supplies infinitely generated free subgroups of finitely generated free groups, yielding a countably infinite-rank free group. Only the publication year is used.',milestones:[{date:'1927',kind:'Published free-subgroup theorem',claim:'An infinitely generated subgroup of a finitely generated free group is free, yielding a countably infinite-rank free group.',source:'schreier1927',facts:['free','!fg']}]},
 dihedral:{firstProof:'2005-10',dateKind:'Earliest located exact exposition; historical upper bound',source:'ggt',note:'Bowditch gives the infinite dihedral group by presentation. The date is a located exact-source upper bound, not a claim about its first historical appearance.',milestones:[]},
 heisenberg:{firstProof:'2005-10',dateKind:'Earliest located exact exposition; historical upper bound',source:'ggt',note:'Bowditch defines the discrete Heisenberg group as the 3 × 3 upper unitriangular matrices over ℤ. The date is an upper bound for an exact source, not historical priority.',milestones:[]},
 lamplighter:{firstProof:'1961',dateKind:'Earliest located exact consequence; historical upper bound',source:'baumslag1961',note:'Baumslag’s 1961 wreath-product theorem applies directly to C₂ ≀ ℤ and proves failure of finite presentability. This dates an exact consequence, not the first construction or naming of the lamplighter group.',milestones:[{date:'1961',kind:'Published property proof',claim:'The lamplighter group is not finitely presented (Baumslag’s wreath-product theorem).',source:'baumslag1961',facts:['!fp']}]},
 grigorchuk:{firstProof:'1980',dateKind:'Original published construction',source:'grigorchuk1980',note:'The infinite finitely generated torsion group was constructed in 1980. Intermediate growth was announced in 1983, with the detailed proof published in 1984.',milestones:[{date:'1980',kind:'Construction',claim:'An infinite finitely generated torsion 2-group.',source:'grigorchuk1980',facts:['!finite','fg','torsion']},{date:'1983',kind:'Published announcement',claim:'The intermediate-growth result was announced.',source:'grigorchuk1983',facts:[]},{date:'1984',kind:'Detailed published proof',claim:'Intermediate growth and the negative solution of Day’s elementary-amenability question.',source:'grigorchuk1984',facts:['intermediate','!ea']}]},
 sl3z:{firstProof:'1967',dateKind:'Earliest located property proof for the exact group; historical upper bound',source:'kazhdan1967',note:'SL₃(ℤ) is far older than property (T). Kazhdan’s 1967 paper supplies a dated exact-group theorem; it is not a construction date for the integer matrix group.',milestones:[{date:'1967',kind:'Published property proof',claim:'Kazhdan’s property (T) for SL₃(ℤ).',source:'kazhdan1967',facts:['t']}]},
 higman:{firstProof:'1951-01',dateKind:'Original published construction',source:'higman1951',note:'Higman’s four-generator group is infinite and has no nontrivial finite quotients. Its acyclicity and finite classifying-space description are documented separately in the modern reference.',milestones:[]},
 grigorchuk98:{firstProof:'1998',dateKind:'Original published proof located',source:'grigorchuk98',note:'A finitely presented amenable group outside the elementary amenable class.',milestones:[{date:'1998',kind:'Published property proof',claim:'Finite presentability, amenability, and failure of elementary amenability for the same group.',source:'grigorchuk98',facts:['fp','amenable','!ea']}]},
 erschler:{firstProof:'2002-05',dateKind:'Earliest located preprint',source:'erschler2002',note:'The IHÉS preprint is dated May 2002; the journal article appeared on 1 February 2004.',milestones:[{date:'2002-05',kind:'Preprint',claim:'Intermediate growth without residual finiteness.',source:'erschler2002',facts:['intermediate','!rf']},{date:'2004-02-01',kind:'Journal publication',claim:'Publication in Journal of Algebra, volume 272.',source:'erschler',facts:[]}]},
 nekrashevych:{firstProof:'2020-08-11',dateKind:'Original construction preprint',source:'nekrashevych2020',note:'This entry is the construction containing the first Grigorchuk group. Earlier simple groups of intermediate growth were announced in a different 2016 paper.',milestones:[{date:'2016-01-06',kind:'Earlier examples in this class',claim:'First simple groups of intermediate growth; not the date of this specific 2020 construction.',source:'nekrashevych2016',facts:[]},{date:'2020-08-11',kind:'Construction preprint',claim:'A simple torsion group of intermediate growth containing the first Grigorchuk group.',source:'nekrashevych2020',facts:['!finite','fg','simple','torsion','intermediate','!exponent']}]},
 thompson:{firstProof:'1965',dateKind:'Construction date reported in the literature',source:'thompson',note:'Cannon–Floyd–Parry (1996) attribute the definitions to Richard Thompson in 1965. Their article is a later source, not a 1965 publication.',milestones:[{date:'1984',kind:'Detailed published property proof',claim:'Brown–Geoghegan establish the infinite-dimensional finiteness properties of F; their result was announced in 1983.',source:'brown1984',facts:[]}]},
 sauers:{firstProof:'2026-08-24',dateKind:'First registered formal proof',source:'palomar',note:'Sauers. The pinned v1 record was mechanically verified at 18:17:14 UTC and registered at 20:15:36 UTC on 24 August 2026.',milestones:[{date:'2026-08-24',kind:'Registered formal proof',claim:'The displayed finitely presented group is sofic and not MF in the Carrión–Dadarlat–Eckhardt operator-norm sense.',source:'palomar',facts:['fp','sofic','!mf']}],priority:{claim:'First non-MF group',attribution:'Sauers (author’s priority claim)',note:'The registry verifies the pinned formal result; its editorial record does not certify novelty.'},formal:{theorem:'ExplicitNonMF.explicit_sofic_not_MF',recordId:'PALOMAR-2026-08-24-000006',version:1,verifiedAt:'2026-08-24T18:17:14Z',commit:'f6ccc7a138b281eb6c4eedf111c6cbd37b4917ce',statement:'https://github.com/SauersML/group-approximation/blob/f6ccc7a138b281eb6c4eedf111c6cbd37b4917ce/Palomar/Challenge.lean',proof:'https://github.com/SauersML/group-approximation/blob/f6ccc7a138b281eb6c4eedf111c6cbd37b4917ce/PalomarSolution.lean',record:'https://data.palomar-registry.org/entries/PALOMAR-2026-08-24-000006-v1.json',assurance:'Palomar reports successful comparison, Lean kernel checking, and NanoDa checking of the pinned proof. Subsequent displayed deductions are not independently Lean-checked.'}}
};
// Additional dated property proofs, kept distinct from first construction dates.
const milestone=(group,date,source,kind,claim,facts)=>history[group].milestones.push({date,source,kind,claim,facts:facts.split(' ')});
milestone('free2','1882','dyck1882','Construction and immediate consequences','The two-generator free construction: free, finitely generated, infinite and nonabelian.','free fg !finite !abelian');
milestone('free2','1929','neumann1929','Published property proof','The rank-two free group is nonamenable.','!amenable');
milestone('free2','1975','powers1975','Published property proof','C*-simplicity and uniqueness of the canonical trace.','cstar utrace');
milestone('free2','1979','haagerup1979','Published property proof','Positive-definite functions vanishing at infinity give the Haagerup property.','haagerup');
milestone('freeinf','1979','haagerup1979','Published property proof','The free-group construction of positive-definite approximations also applies to countable rank.','free haagerup');
milestone('prufer','1923','prufer1923','Construction and immediate consequences','The quasicyclic primary group is infinite, abelian, torsion and divisible.','!finite abelian torsion divisible');
milestone('higman','1951-01','higman1951','Published construction','The four-generator presentation defines an infinite torsion-free group with no nontrivial finite quotients.','fp !finite tf !rf');
milestone('higman','1980-01','bdh1980','Published property proof','Acyclicity and a finite two-dimensional classifying space.','acyclic finite_cd finfty');
milestone('grigorchuk','1984','grigorchuk1984','Published property proof','A recursive contraction algorithm solves the word problem.','word');
milestone('higman','2005-06-10','higman','Located proof; historical upper bound','Theorem 8 and Corollary 9: an acyclic group with a finite two-dimensional classifying space. Earlier work is cited there.','acyclic finite_cd finfty');
milestone('thompson','1984','brown1984','Published property proof','A finite-type classifying space establishes type F∞; the group is torsion-free.','finfty tf');
for(const group of ['z','z2','q'])milestone(group,'1929','neumann1929','Published class theorem','Abelian groups admit invariant means. Applied to this classical abelian example.','abelian amenable');
for(const group of ['free2','freeinf'])milestone(group,'2008-04-24','approximation','Located proof; historical upper bound','Examples 4.2–4.3 document residual finiteness and soficity of free groups.','free rf sofic');
history.fournier_facio.milestones.push({date:'2026-08-14',kind:'Revised preprint',claim:'Version 2 contains small changes following comments on v1.',source:'ff2026revision',facts:[]});
for(const h of Object.values(history))h.milestones.sort((a,b)=>compareDates(a.date,b.date));
// A year/month-only proof is placed at the end of its known period. This is
// an internal conservative bound; the UI retains the original date precision.
export function dateBoundary(date){
 if(date.length===4)return `${date}-12-31`;
 if(date.length===7){const [year,month]=date.split('-').map(Number);return `${date}-${new Date(Date.UTC(year,month,0)).getUTCDate()}`;}
 return date;
}
export function compareDates(a,b){return dateBoundary(a).localeCompare(dateBoundary(b));}
export function formatDate(date){
 if(date===null)return 'Not established';
 if(/^\d{4}$/.test(date))return date;
 if(/^\d{4}-\d{2}$/.test(date))return new Intl.DateTimeFormat('en',{year:'numeric',month:'short',timeZone:'UTC'}).format(new Date(`${date}-01T12:00:00Z`));
 return new Intl.DateTimeFormat('en',{year:'numeric',month:'short',day:'numeric',timeZone:'UTC'}).format(new Date(`${date}T12:00:00Z`));
}
